import type { ColorTheme } from "../tokens/colors";

export const paperTheme: ColorTheme = {
	"color.background.app": "#FAF9F6",
	"color.background.reader": "#FFFFFF",
	"color.background.canvas": "#F5F4F1",
	"color.background.sidebar": "#FDFCFA",
	"color.background.navigation": "#FAF9F6",
	"color.background.modal": "#FFFFFF",
	"color.background.popover": "#FFFFFF",
	"color.background.tooltip": "#2E2B27",
	"color.background.sheet": "#FFFFFF",
	"color.background.overlay": "rgba(31, 34, 41, 0.24)",
	"color.background.dropdown": "#FFFFFF",
	"color.background.selection": "#DBE6FF",
	"color.background.scrim": "rgba(31, 34, 41, 0.48)",
	"surface.base": "#FFFFFF",
	"surface.raised": "#F9F8F6",
	"surface.elevated": "#FFFFFF",
	"surface.floating": "#FFFFFF",
	"surface.sunken": "#F5F4F1",
	"surface.hover": "#F2F1EE",
	"surface.active": "#EBEAE6",
	"surface.pressed": "#E3E1DC",
	"surface.disabled": "#F5F4F1",
	"surface.inverse": "#2E2B27",
	"card.default": "#FFFFFF",
	"card.hover": "#F9F8F6",
	"card.selected": "#F2ECFF",
	"card.active": "#EBEAE6",
	"card.disabled": "#F5F4F1",
	"card.border": "#E9E4DC",
	"card.shadow": "rgba(31, 34, 41, 0.05)",
	"card.overlay": "linear-gradient(transparent, rgba(46,43,39,0.08))",
	"text.primary": "#1F2229",
	"text.secondary": "#5E5C58",
	"text.muted": "#6E6A62",
	"text.disabled": "#9A9690",
	"text.inverse": "#FFFFFF",
	"text.accent": "#365BFF",
	"text.link": "#365BFF",
	"text.visited": "#6B4FCD",
	"text.selection": "#1F2229",
	"text.success": "#2F7A4A",
	"text.warning": "#A16207",
	"text.danger": "#B91C1C",
	"text.info": "#2A4FD1",
	"text.premium": "#7C5CFF",
	"text.metadata": "#6B6860",
	"text.placeholder": "#7A7A72",
	"border.default": "#E9E4DC",
	"border.subtle": "#F0EDE8",
	"border.strong": "#D4CFC6",
	"border.focus": "#365BFF",
	"border.divider": "#F0EDE8",
	"border.input": "#D8D3CC",
	"border.card": "#E9E4DC",
	"border.reader": "#E9E4DC",
	"border.modal": "#E9E4DC",
	"border.selection": "#365BFF",
	"border.hover": "#C8C6C0",
	"button.primary.background": "#365BFF",
	"button.primary.background.hover": "#2A4FD1",
	"button.primary.background.pressed": "#1E3FA8",
	"button.primary.background.disabled": "#DBE6FF",
	"button.primary.foreground": "#FFFFFF",
	"button.primary.foreground.hover": "#FFFFFF",
	"button.primary.border": "transparent",
	"button.primary.shadow": "rgba(59, 101, 255, 0.25)",
	"button.primary.focus.ring": "#365BFF",
	"button.secondary.background": "#F2F1EE",
	"button.secondary.background.hover": "#E9E4DC",
	"button.secondary.foreground": "#1F2229",
	"button.ghost.background": "transparent",
	"button.ghost.background.hover": "#F2F1EE",
	"button.ghost.foreground": "#1F2229",
	"button.outlined.background": "transparent",
	"button.outlined.border": "#D8D3CC",
	"button.outlined.foreground": "#1F2229",
	"button.destructive.background": "#DC2626",
	"button.destructive.background.hover": "#B91C1C",
	"button.destructive.foreground": "#FFFFFF",
	"button.success.background": "#22C55E",
	"button.success.background.hover": "#16A34A",
	"button.success.foreground": "#FFFFFF",
	"button.warning.background": "#F59E0B",
	"button.warning.background.hover": "#D97706",
	"button.warning.foreground": "#1F2229",
	"button.reader.background": "#FFFFFF",
	"button.reader.background.hover": "#F5F4F1",
	"button.reader.foreground": "#365BFF",
	"button.floating.background": "#365BFF",
	"button.floating.foreground": "#FFFFFF",
	"button.toolbar.background": "transparent",
	"button.toolbar.background.hover": "#F2F1EE",
	"button.toolbar.foreground": "#5E5C58",
	"input.background": "#F5F4F1",
	"input.background.hover": "#F2F1EE",
	"input.background.focus": "#FFFFFF",
	"input.foreground": "#1F2229",
	"input.border": "#D8D3CC",
	"input.border.focus": "#365BFF",
	"input.placeholder": "#7A7A72",
	"input.selection.background": "#DBE6FF",
	"input.selection.foreground": "#1F2229",
	"status.success.background": "#DCFCE7",
	"status.success.foreground": "#166534",
	"status.warning.background": "#FEF3C7",
	"status.warning.foreground": "#92400E",
	"status.danger.background": "#FEE2E2",
	"status.danger.foreground": "#991B1B",
	"status.info.background": "#DBEAFE",
	"status.info.foreground": "#1E40AF",
	"status.premium.background": "#F3E8FF",
	"status.premium.foreground": "#6B21A8",
	"status.vip.background": "#F3E8FF",
	"status.vip.foreground": "#6B21A8",
	"status.archived.background": "#F2F1EE",
	"status.archived.foreground": "#6B6860",
	"status.reading.background": "#DBE6FF",
	"status.reading.foreground": "#1E40AF",
	"status.completed.background": "#DCFCE7",
	"status.completed.foreground": "#166534",
	"status.dropped.background": "#FEE2E2",
	"status.dropped.foreground": "#991B1B",
	"status.paused.background": "#FEF3C7",
	"status.paused.foreground": "#92400E",
	"status.processing.background": "#DBEAFE",
	"status.processing.foreground": "#1E40AF",
	"status.queued.background": "#F2F1EE",
	"status.queued.foreground": "#6B6860",
	"status.failed.background": "#FEE2E2",
	"status.failed.foreground": "#991B1B",
	"progress.track": "#F5F4F1",
	"progress.fill": "#365BFF",
	"progress.glow": "#8AABFF",
	"progress.completed": "#22C55E",
	"progress.reader": "#365BFF",
	"progress.audio": "#365BFF",
	"progress.chapter": "#365BFF",
	"progress.loading": "#365BFF",
	"reader.background": "#FAF9F6",
	"reader.surface": "#FFFFFF",
	"reader.toolbar.background": "#FFFFFF",
	"reader.toolbar.foreground": "#1F2229",
	"reader.controls.background": "#F5F4F1",
	"reader.controls.foreground": "#365BFF",
	"reader.paragraph": "#1F2229",
	"reader.heading": "#1F2229",
	"reader.muted": "#6B6860",
	"reader.highlight": "#DBE6FF",
	"reader.accent": "#365BFF",
	"reader.accent.hover": "#2A4FD1",
	"reader.selection.background": "#DBE6FF",
	"reader.selection.foreground": "#1F2229",
	"reader.bookmark.background": "#365BFF",
	"reader.annotation.background": "#F5F4F1",
	"reader.search.highlight": "#FEF3C7",
	"reader.sentence": "#DBE6FF",
	"reader.word": "#365BFF",
	"reader.wordHighlight": "#8AABFF",
	"reader.overlay": "rgba(31, 34, 41, 0.24)",
	"reader.popup.background": "#FFFFFF",
	"reader.translation.background": "#FFFFFF",
	"reader.tts.background": "#FFFFFF",
	"reader.floating.background": "#FFFFFF",
	"shadow.elevation-0": "none",
	"shadow.elevation-1": "0 1px 2px 0 rgba(31, 34, 41, 0.04)",
	"shadow.elevation-2": "0 1px 3px -1px rgba(31, 34, 41, 0.05)",
	"shadow.elevation-3": "0 4px 10px -4px rgba(31, 34, 41, 0.06)",
	"shadow.elevation-4": "0 10px 24px -8px rgba(31, 34, 41, 0.09)",
	"shadow.elevation-5": "0 20px 32px -12px rgba(31, 34, 41, 0.18), 0 8px 16px -8px rgba(31, 34, 41, 0.08)",
	"shadow.focus": "0 0 0 3px rgba(59, 101, 255, 0.25)",
	"overlay.modal": "rgba(31, 34, 41, 0.48)",
	"overlay.backdrop": "rgba(31, 34, 41, 0.48)",
	"overlay.glass": "rgba(255, 255, 255, 0.84)",
	"overlay.popover": "rgba(31, 34, 41, 0.24)",
	"overlay.tooltip": "#2E2B27",
	"overlay.dropdown": "#FFFFFF",
	"overlay.sheet": "rgba(31, 34, 41, 0.48)",
	"overlay.drawer": "rgba(31, 34, 41, 0.48)",
	"overlay.dialog": "rgba(31, 34, 41, 0.48)",
	"overlay.hover-card": "#FFFFFF",
};
