export interface ResourceDefinition {
  key: string;
  name: string;
  description: string;
  category: string;
  actions: string[];
  isSystem?: boolean;
  isEnabled?: boolean;
}

export const RESOURCES: ResourceDefinition[] = [
  {
    key: 'novels',
    name: 'Catalog Novels',
    description: 'Public catalog novels.',
    category: 'catalog',
    actions: ['list', 'read', 'create', 'update', 'delete', 'manage'],
    isSystem: true,
  },
  {
    key: 'library',
    name: 'Personal Library',
    description: 'User-specific library entries.',
    category: 'library',
    actions: ['read', 'add', 'update', 'delete', 'manage'],
    isSystem: true,
  },
  {
    key: 'chapters',
    name: 'Chapters',
    description: 'Translated and raw chapters.',
    category: 'chapters',
    actions: ['list', 'read', 'read_raw', 'translate', 'visit', 'manage'],
    isSystem: true,
  },
  {
    key: 'jobs',
    name: 'Background Jobs',
    description: 'Background scraper jobs and tasks.',
    category: 'jobs',
    actions: ['list', 'retry', 'manual_intervention', 'import', 'scrape', 'manage'],
    isSystem: true,
  },
  {
    key: 'authors',
    name: 'Authors',
    description: 'Author taxonomy.',
    category: 'taxonomy',
    actions: ['list', 'read', 'create', 'update', 'delete', 'manage'],
    isSystem: true,
  },
  {
    key: 'genres',
    name: 'Genres',
    description: 'Genre taxonomy.',
    category: 'taxonomy',
    actions: ['list', 'read', 'create', 'update', 'delete', 'manage'],
    isSystem: true,
  },
  {
    key: 'publication_statuses',
    name: 'Publication Statuses',
    description: 'Publication status taxonomy.',
    category: 'taxonomy',
    actions: ['list', 'read', 'create', 'update', 'delete', 'manage'],
    isSystem: true,
  },
  {
    key: 'settings',
    name: 'Settings',
    description: 'User settings.',
    category: 'settings',
    actions: ['read', 'update', 'manage'],
    isSystem: true,
  },
  {
    key: 'profile',
    name: 'Profile',
    description: 'Current user profile.',
    category: 'user',
    actions: ['read', 'update', 'manage'],
    isSystem: true,
  },
  {
    key: 'sessions',
    name: 'Reading Sessions',
    description: 'Re-read sessions.',
    category: 'sessions',
    actions: ['read', 'manage'],
    isSystem: true,
  },
  {
    key: 'pronunciation',
    name: 'Pronunciation Rules',
    description: 'TTS pronunciation rules.',
    category: 'tts',
    actions: ['read', 'manage'],
    isSystem: true,
  },
  {
    key: 'translation',
    name: 'Translation',
    description: 'Raw chapter translation.',
    category: 'translation',
    actions: ['execute', 'manage'],
    isSystem: true,
  },
  {
    key: 'cover',
    name: 'Cover Images',
    description: 'Cover image sync and management.',
    category: 'catalog',
    actions: ['sync', 'manage'],
    isSystem: true,
  },
  {
    key: 'users',
    name: 'Users',
    description: 'User accounts.',
    category: 'administration',
    actions: ['list', 'read', 'create', 'update', 'delete', 'manage'],
    isSystem: true,
  },
  {
    key: 'roles',
    name: 'Roles',
    description: 'RBAC roles.',
    category: 'administration',
    actions: ['list', 'read', 'create', 'update', 'delete', 'manage'],
    isSystem: true,
  },
  {
    key: 'groups',
    name: 'Access Groups',
    description: 'RBAC access groups.',
    category: 'administration',
    actions: ['list', 'read', 'create', 'update', 'delete', 'manage'],
    isSystem: true,
  },
  {
    key: 'resources',
    name: 'Resources',
    description: 'System resources and feature toggles.',
    category: 'administration',
    actions: ['list', 'read', 'enable'],
    isSystem: true,
  },
  {
    key: 'audit_logs',
    name: 'Audit Logs',
    description: 'Security audit logs.',
    category: 'administration',
    actions: ['read', 'manage'],
    isSystem: true,
  },
  {
    key: 'access_logs',
    name: 'Access Logs',
    description: 'Resource access logs.',
    category: 'administration',
    actions: ['read', 'manage'],
    isSystem: true,
  },
  {
    key: 'admin',
    name: 'Admin Console',
    description: 'Admin console access and management.',
    category: 'administration',
    actions: ['access', 'manage'],
    isSystem: true,
  },
  {
    key: 'service',
    name: 'Service',
    description: 'Service/bot account access.',
    category: 'service',
    actions: ['read', 'execute', 'manage'],
    isSystem: true,
  },
];
